#Phase 1: Data Selection
##1. Project Goal
The goal of this project is to analyze students’ performance using data mining techniques. The project will focus on classification and clustering tasks. Classification will be used to predict students’ academic performance based on their characteristics, while clustering will be used to identify groups of students with similar characteristics.

## 2. Dataset Source
Dataset Name: Students Performance

Dataset Source: Kaggle

URL: https://www.kaggle.com/datasets/rabieelkharoua/students-performance-dataset

## 3. Dataset Description
###A. Number of Attributes
The dataset contains 15 attributes

###B. Data Types
The dataset contains 13 integer attributes (int64) and 2 floating-point attributes (float64).

### C. Number of Records
The dataset contains 2,392 records (students).

###D. Class Attribute
The class attribute is GradeClass.
It represents the students' academic performance class.

######E. Class Distribution
The dataset contains five classes in the GradeClass attribute. The number of students in each class is shown below:
| GradeClass | Number of Students |
|------------|-------------------:|
| 0 | 107 |
| 1 | 269 |
| 2 | 391 |
| 3 | 414 |
| 4 | 1211

##F. Sample of Raw Dataset
The following table shows a sample of the raw dataset:

In [1]:
import pandas as pd
df = pd.read_csv("Raw_dataset.csv")
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4

In [2]:
df.shape

(2392, 15)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   int64
dtypes: float64(2), int64(13)
memory usage: 280.4 KB

In [4]:
df["GradeClass"].value_counts().sort_index()

GradeClass
0     107
1     269
2     391
3     414
4    1211
Name: count, dtype: int64